#pragma once
#include<iostream>

class MeshUnion
{
public:
	MeshUnion() ;

	~MeshUnion();

	void ncdim_read();
	void ncvar_read(double *&meshunion_data, std::string ncvarname, int &dim1, int &dim2);
	void ncvar_read(double *&meshunion_data, std::string ncvarname, int &dim1);

	int K;
	int Nv;
	int	Ne_inner;
	int Ne_boundary;
	int Nfp;
	int Np;
	int cell_Nv;
	int cell_Nq;
	int two = 2;
	int one = 1;

	double*BoundaryEdge_FToE;
	double*BoundaryEdge_FToF;
	double*BoundaryEdge_FToM;
	double*BoundaryEdge_FToN1;
	double*BoundaryEdge_FToN2;
	double*BoundaryEdge_FToV;
	double*BoundaryEdge_ftype;
	double*BoundaryEdge_Js;
	double*BoundaryEdge_LAV;
	double*BoundaryEdge_M;
	double*BoundaryEdge_Ne;
	double*BoundaryEdge_Nfp;
	double*BoundaryEdge_nx;
	double*BoundaryEdge_ny;
	double*BoundaryEdge_nz;
	double*BoundaryEdge_r;
	double*BoundaryEdge_xb;
	double*BoundaryEdge_yb;
	double*cell_Dr;
	double*cell_Ds;
	double*cell_Dt;
	double*cell_EToV;
	double*cell_faceType;
	double*cell_Fmask;
	double*InnerEdge_cell_FToV;
	double*cell_invM;
	double*cell_LAV;
	double*cell_M;
	double*cell_N;
	double*cell_Nface;
	double*cell_Nfp;
	double*cell_Nfv;
	double*cell_Np;
	//double*cell_Nq;
	//double*cell_Nv;
	double*cell_r;
	double*cell_rq;
	double*cell_s;
	double*cell_sq;
	double*cell_t;
	double*cell_TNfp;
	double*cell_tq;
	double*cell_type;
	double*cell_V;
	double*cell_Vq;
	double*cell_vr;
	double*cell_vs;
	double*cell_vt;
	double*cell_wq;
	double*charLength;
	double*EToE;
	double*EToF;
	double*EToM;
	double*EToR;
	double*EToV;
	double*ind;
	double*InnerEdge_cell_Dr;
	double*InnerEdge_cell_Ds;
	double*InnerEdge_cell_Dt;
	double*InnerEdge_cell_faceType;
	double*InnerEdge_cell_Fmask;
	double*InnerEdge_cell_invM;
	double*InnerEdge_cell_LAV;
	double*InnerEdge_cell_M;
	double*InnerEdge_cell_N;
	double*InnerEdge_cell_Nface;
	double*InnerEdge_cell_Nfp;
	double*InnerEdge_cell_Nfv;
	double*InnerEdge_cell_Np;
	double*InnerEdge_cell_Nq;
	double*InnerEdge_cell_Nv;
	double*InnerEdge_cell_r;
	double*InnerEdge_cell_rq;
	double*InnerEdge_cell_s;
	double*InnerEdge_cell_sq;
	double*InnerEdge_cell_t;
	double*InnerEdge_cell_TNfp;
	double*InnerEdge_cell_tq;
	double*InnerEdge_cell_type;
	double*InnerEdge_cell_V;
	double*InnerEdge_cell_Vq;
	double*InnerEdge_cell_vr;
	double*InnerEdge_cell_vs;
	double*InnerEdge_cell_vt;
	double*InnerEdge_cell_wq;
	double*InnerEdge_FToE;
	double*InnerEdge_FToF;
	double*InnerEdge_FToM;
	double*InnerEdge_FToN1;
	double*InnerEdge_FToN2;
	double*InnerEdge_FToV;
	double*InnerEdge_Js;
	double*InnerEdge_LAV;
	double*InnerEdge_M;
	double*InnerEdge_Ne;
	double*InnerEdge_Nfp;
	double*InnerEdge_nx;
	double*InnerEdge_ny;
	double*InnerEdge_nz;
	double*InnerEdge_r;
	double*J;
	//double*K;
	double*LAV;
	//double*Nv;
	double*rx;
	double*ry;
	double*rz;
	double*status;
	double*sx;
	double*sy;
	double*sz;
	double*tx;
	double*ty;
	double*type;
	double*tz;
	double*vx;
	double*vy;
	double*vz;
	double*x;
	double*xc;
	double*y;
	double*yc;
	double*z;
	double*zc;
};

